### ISSUE TITLE
Improve performance on loading times

### ISSUE THREAD

**Issue by brupelo** [brupelo/pyblime#19]
Using `load_syntax_set` is terribly expensive on my laptop... loading the Sublime syntax files from `3149`  takes almost 4s! That's crazy :(

Scripts/apps using pyblime should be loaded in <1s avg... other than that I call it a bug.

How to address this one? Maybe load syntax files on-demand only and using file modified_times or file checksums? Just thinking loud here... :/

Ps. I'm aware syntect uses a compiled version of the syntax files... but I'd like using specifically "my" syntax files, not the ones provided by syntect

**Comment by keith-hall** [comment]
when you close an issue, it could be useful to say why its closed - how the feature/fix was implemented etc. so its clear that it was fixed as opposed to abandoned ;)
for this one, I guess you can (re)compile your syntax set whenever a syntax definition has a newer modified time than the compile time...

**Comment by brupelo** [comment]
Oh, sorry, I hadn't commented cos I thought nobody was tracking other than me... btw... do you get notifications each time I open/close issues?

In any case, not sure why this had been solved but few days ago loading a whole folder was terribly expensive but nowadays it loads the whole thing pretty fast, you can see one of the screenshots in the landing page... Not sure if it's related to the fact I'd got rid of some crazy files (rust parser of 6000 lines) to convert the project from "rust" to "python"... In any case, can't give you a good explanation cos honestly? I don't even know... but it just works fast now lol ;)

**Comment by keith-hall** [comment]
haha understood, thanks for the explanation ;) yes, I do get notifications :) it can be useful to comment even if nobody gets notified due to hypothetical scenarios where, in the future, when the project is popular, someone else experiences the same issue, finds this closed ticket and wants to know whether/how it was solved ;)
